### ISSUE TITLE
Sheet is Different

### ISSUE THREAD

**Issue by dsakura** [MasterTomNL/mastertomnl-domain-sheet#1]
The installed sheet is different from the one that appears on the project page. No officers tab and some formatting errors. Many thanks.
<a href="https://ibb.co/kMC0fFP"><img src="https://i.ibb.co/FnTJMtd/sheeterror.png" alt="sheeterror" border="0"></a>

**Comment by MasterTomNL** [comment]
Thanks for your feedback!
I've updated the module to fix these issues.

You can simply update the module now through the Foundry Add-on module interface.
